### ISSUE TITLE
My Akai MPK mini does not respond well to light-control note_on messages

### ISSUE THREAD

**Issue by alextz** [bberthelemy/apc-mini-lights-controller#2]
I was thrilled to find your light-control Python logic a couple hours ago. On my machine, the lights turn off if they get any note-on message, no matter what the velocity/color is.

> It's actually more complex than that. The Arpeggiator ON/OFF light turns off no matter what light number is sent. And, the BANK A/B light (25) turns off only if it's green. And other odd things. But they all only turn off. I cannot turn on any light.

I don't have a DAW, so all communications with the MPK is with my own Python script. My script uses the MPK's keys, pads, and knobs without trouble. And read/writes the MPK programming.

The only ideas I have for why my lights don't work as yours do are:

1) I've not updated my firmware and you have.
2) Your DAW has initialized your MPK in some needed way.

In response to this ID request message:
`mido.Message('sysex', data = [ 0x7e, 0x7f, 0x06, 0x01, ])`

my MPK sends:

`sysex data=(126,127,6,2,71,38,0,25,0,34,0,34,0,0,0,0,0,0,0,4,0,0,0,3,1,0,0,48,49,50,51,52)`

which doesn't look very helpful. :)

Anyway, do you have any ideas what might be going on?

Thanks,

Alex

**Comment by alextz** [comment]
Oh foo. I just found a video that shows your script running: https://youtu.be/9KhLs2uHBk8

Completely different device.

Mine:

![akai_pro_mini](https://user-images.githubusercontent.com/1121327/85217121-146b2100-b342-11ea-9578-f5fd389b6bb8.jpg)

**Comment by ingenieur-du-grenier** [comment]
yes sorry mate, this is a script for the "AKAI APC MINI" only, the protocol for the MPK MINI is a bit different and I would need a device to develop another script. Unfortunately I don't have any ...

I hope you will find what you need on the web

**Comment by alextz** [comment]
Thanks! No worries.

To note for anyone else with an Akai MPK Pro Mini looking for how to control the lights on and off:

Send "**`note_on   channel:0   note:light_number   velocity:0_or_127`**" to the device. Velocity zero turns off the light. 127 turns it on. Light numbers are 3..7 9..16 25..27 for the visible groups of 5, 8, and 3 lights on the device, respectively.

The picture I posted is from the Windows control program, not the device.
